@startuml
start
:Открыть форму расчета;
:Ввести параметры сделки;

while (Данные корректны?) is (нет)
  :Показать ошибки валидации;
  :Исправить данные;
endwhile (да)

:Получить переменные и нормативы;
:Определить тип контрагента;
:Выбрать стратегию расчета;
:Выполнить расчет;
:Показать результат;

if (Дальнейшее действие?) then (Черновик)
  :Сохранить черновик отчета;
elseif (Итоговый отчет)
  :Сохранить итоговый отчет;
else (Отмена)
  stop
endif

:Показать подтверждение;
if (Открыть историю?) then (Да)
  :Открыть историю отчетов;
endif
stop
@enduml
